#!/bin/zsh
if test ! -d /var/chef-solo/repo
then
  git clone git@github.com:youroute/youroute-chef-repo.git /var/chef-solo/repo
fi
cd /var/chef-solo/repo
git pull
librarian-chef install --verbose
git clone git://github.com/youroute/youroute-cookbook.git cookbooks/youroute
sudo chef-solo -c /var/chef-solo/solo.rb -j /var/chef-solo/node.json