set['localegen']['lang'] = [ "en_GB.UTF-8 UTF-8", "ru_RU.UTF-8 UTF-8" ]
set['locale']['lang'] = "en_US.UTF-8"
set['zsh']['users'] = ['vagrant']
set['ohmyzsh']['theme'] = "robbyrussell"
set['ohmyzsh']['users'] = [ "vagrant" ]
set['mysql']['server_root_password'] = "qweqwe"
set['mysql']['bind_address'] = "127.0.0.1"
set['rbenv']['group_users'] = ['vagrant']
set['nginx']['worker_processes'] = 2
set['nginx']['gzip_comp_level'] = 5
# set[:postgresql][:password][:postgres] = "qweqwe"